### ISSUE TITLE
Proxy is not defined

### ISSUE THREAD

**Issue by aerlaut** [Naltox/telegram-node-bot#102]
error in `localization/Ivan.js:41` : `ReferenceError: Proxy is not defined`

**Comment by ovuncmetin** [comment]
Same issue, any solution?

**Comment by ZaphodBBX** [comment]
Try to use node > v6.0 

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Proxy

**Comment by fredleger** [comment]
I confirm upgrading nodejs do the trick
