### ISSUE TITLE
Global Proxy Support

### ISSUE THREAD

**Issue by fredleger** [Naltox/telegram-node-bot#105]
Hi, 

I was trying to dev a small bot for work and i ran into an issue with http proxies.
We have a mandatory corporate proxy (without authentification though) that i have to go through. I looked over and it seems there is no way to define a proxy globally for nodejs and this will lead to this error : 

```
[error]
Network error: Error: connect ETIMEDOUT 149.154.167.198:443
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
request TelegramApiRequest {
  _method: 'getUpdates',
  _params: { timeout: 50, offset: 0 },
  _multipart: undefined }


[log]
Retry request TelegramApiRequest {
  _method: 'getUpdates',
  _params: { timeout: 50, offset: 0 },
  _multipart: undefined }
```

Is there anyway to integrate a proxy support in this project ? 

In my understanding there is 2 options : 
- this might be done upstream with tiny_requests
- or we could use another request abstraction module that support it

Frederic

**Comment by Naltox** [comment]
I think you can use proxy before node

**Comment by jclohmann** [comment]
I have the same problem. Every request times out after 50 seconds.
My $HTTP_PROXY and $HTTPS_PROXY environment variables are set and working with other programs.

@fredleger have you found a solution?
