### ISSUE TITLE
Using API to send menu to a user.

### ISSUE THREAD

**Issue by mauris** [Naltox/telegram-node-bot#106]
Currently I have a bot that allows users to enter commands in a group chat, in which some of these commands are confirmed with the user who wrote the command by a private message. I wish to show a yes / no menu so that user can respond to the PM to confirm the command.

I can send a PM message using the user's ID. There is `$.runMenu`, but the API `this._api` does not provide `runMenu`. I was looking at `ReplyKeyboardMarkup` and `KeyboardButton` but they are not exposed to the developer.

**Comment by Naltox** [comment]
You cant use 'runMenu' feature outside from controllers, `ReplyKeyboardMarkup` and `ReplyKeyboardMarkup` are in Telegram.Models
