### ISSUE TITLE
ending a  inline menu?

### ISSUE THREAD

**Issue by paOol** [Naltox/telegram-node-bot#107]
I would like to clear the message, or at least edit the initial message of any inline buttons.

I tried some stuff in the callback , but it just added messages into the chat rather than removing or editing the initial inline menu.

has anyone come up with a solution?

**Comment by lenny76** [comment]
+1

**Comment by bidadh** [comment]
+1

**Comment by paOol** [comment]
editing the original message of an inline menu worked on a different bot I tested, so it's definitely possible with telegram's API.

**Comment by Naltox** [comment]
You can use sub menus in `runInlineMenu`  - https://github.com/Naltox/telegram-node-bot#inline-menu

Or you can manual edit message by id using `editMessageText` method in api

**Comment by paOol** [comment]
```
    $.runInlineMenu({
          method: 'sendMessage',
          params: [`Image Results for ${query}`],
          menu: [{
            text: 'Find another result',
            callback: (callbackQuery) => {
              let id = $.message;
              console.log(id);
```

that gives me the message ID of the user who entered the command.
how do I get the message ID of the runInlineMenu?

**Comment by AndryFM** [comment]
I use this way:

```
{
    text: 'Yes!',
        callback: (callbackQuery, message) => {
            $.api.editMessageText('new text', { chat_id: $.chatId, message_id: message.messageId })
    }
},
```

**Comment by rotimi-best** [comment]
@AndryFM Thanks. This worked but my inline buttons disappear. How do I do it in such a way that they don't disappear?

**Image before clicking inline button:**
![image](https://user-images.githubusercontent.com/31730715/48972764-7e262a80-f03a-11e8-9f84-cdfbad3d2142.png)

**Image after clicking inline button:**
![image](https://user-images.githubusercontent.com/31730715/48972768-98600880-f03a-11e8-97a7-6e776d6c4b82.png)
