### ISSUE TITLE
inline keyboard support ?

### ISSUE THREAD

**Issue by rsklyar** [Naltox/telegram-node-bot#11]
https://core.telegram.org/bots/2-0-intro#new-inline-keyboards

**Comment by Naltox** [comment]
Yes! Just updated module

**Comment by rsklyar** [comment]
Great! Thank you!

**Comment by vbifonixor** [comment]
Sorry, but it seems to be that original scope methods don't work when calling in an inline keyboard's callback functions

**Comment by rsklyar** [comment]
(

**Comment by paOol** [comment]
Is there support for callback_data? 
as well as Updating messages?

Can you show an example of inline buttons for the following situation?

-User types /command
-bot responds with inline keyboard [ desktop, tablet, mobile],
-user picks one
-bot saves response and updates message with more inline buttons [highest, medium, smallest],
-user picks again
-bot asks for a URL
-user enters url
-bot does stuff based on the given parameters

I am trying to log the button response, but can't seem to figure it out

```
  {
                text: '1',
                callback_data : '1',
                callback: ($) => {
                    console.log($.message.text)
                   // does not retrieve '1' like expected.
                }
  },
```
