### ISSUE TITLE
New issues with framework

### ISSUE THREAD

**Issue by VitaliyR** [Naltox/telegram-node-bot#116]
- Access to localization in Inline & Callback controllers? Why is it only accessible in Base?
- Access to localization via this.localization but not `this._localization`. I saw in MessageUpdateProcessor.js:58 `controller.localization = this._dataSource.localization` but it not sets.
- Inline Scope doesn't have scope extension support. Why?
- Scope.runInlineMenu has inconsistent API while using it with new and previous message. Take a look:

**New Message:**

``` js
$.runInlineMenu({ 
  method: 'sendMessage',
  params: [ 'Text', { parse_mode: 'Markdown' } ]
});
```

**Previous Message:**

``` js
const msg = new Telegram.Models.Message(...);
$.runInlineMenu({
   method: 'sendMessage',
   message: 'Text',
   params: [msg]  // can't pass options for message -> can't apply Markdown to it
}, msg);
```
- **Does somebody still maintains it?**

**Comment by Naltox** [comment]
@VitaliyR 
Hey!

I will fix these bugs soon!
