### ISSUE TITLE
error TypeError: $.waitForRequest is not a function

### ISSUE THREAD

**Issue by dleonext** [Naltox/telegram-node-bot#117]
Hello!
I'm getting this error that I never got before. 
I just updated to the newer version of telegram-node-bot.

`error TypeError: $.waitForRequest is not a function`

```
class HelloController extends TelegramBaseController {

  helloWorldHandler($){
    $.sendMessage('Hello!');
    $.waitForRequest(($) => {

                var input = $.message.text;
        $.sendMessage("User input " + input);

            });
  }

  get routes() {
    return {
      '/hello' : 'helloWorldHandler'
    }
  }
}

tg.router.
when(['/hello'], new HelloController())

```

The strange thing is that I can use the `$.sendMessage` in the same context .

Cheers.

**Comment by Naltox** [comment]
@dleonext 
Hi! waitForRequest not a function, its a property, so you must use it like this:

``` js
$.waitForRequest
   .then($ => {

   })
```

**Comment by dleonext** [comment]
@Naltox thanks for the reply!
I think there's a lack of documentation here...

> waitForRequest
> Messages controller scope has waitForRequest method after calling that the next update from current user will be passed to promise.

cheers.
