### ISSUE TITLE
How can reply message in the group.

### ISSUE THREAD

**Issue by lamjack** [Naltox/telegram-node-bot#118]
hello,

Very thanks for this project, it's very useful,

im a phper so not very familiar with nodejs.

i try to run the demo code, it's work. but when i was added my bot in the group, cannot reply anything.

could u give me some tips?

and one more question, because i maintain some servers, when the servers die, will call my report api on time, but i want send the error notice to telegram app some specifie account or group, how can i do it?

thanks very much.

**Comment by Naltox** [comment]
@lamjack Check that you enabled receiving all messages from groups in @BotFather
