### ISSUE TITLE
Web process failed to bind to $PORT within 60 seconds of launch

### ISSUE THREAD

**Issue by rmnblm** [Naltox/telegram-node-bot#119]
When I deploy a Telegram bot built with this module to Heroku, after 60 seconds I get following error:

```
2016-09-20T11:50:11.599886+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2016-09-20T11:50:11.599886+00:00 heroku[web.1]: Stopping process with SIGKILL
2016-09-20T11:50:11.705966+00:00 heroku[web.1]: Process exited with status 137
```

I couldn't find a way to set a port because there is no `.listen(...)` method when calling the Telegram constructor. Any ideas?

**Comment by rmnblm** [comment]
Might be resolved with PR https://github.com/Naltox/telegram-node-bot/pull/98

**Comment by rmnblm** [comment]
I solved the problem by using a `Procfile` with the following content:

```
worker: node index.js
```

I did also run the following command

```
$ heroku scale web=0 worker=1
```

**Comment by vincentaudebert** [comment]
Watch out. This doesn't work on a free dyno.

**Comment by MetaNaveen** [comment]
**The below steps resolved my solution:**

Editing package.json as:

...
"engines": {
"node": "5.0.0",
"npm": "4.6.1"
},
...

and Server.js as:

...
var port = process.env.PORT || 3000;
app.listen(port, "0.0.0.0", function() {
console.log("Listening on Port 3000");
});
...

**Comment by johnKHill** [comment]
Thank you. This worked for me 100%.

var port = process.env.PORT || 3000;
app.listen(port, "0.0.0.0", function() {
console.log("Listening on Port 3000");
});

**Comment by rajanbhadauria** [comment]
var express = require('express');
var path = require('path');
var app = express();

global.appRoot = path.resolve(__dirname);


var port = process.env.PORT | 8000;


app.use(express.static(appRoot + '/public/dist'));


app.listen(port, '0.0.0.0', function() {
    console.log("Listening on Port "+port);
    });

I have the same issue but not able to fix it
Please help me to fix it

**Comment by MonX94** [comment]
> Watch out. This doesn't work on a free dyno.

It did.

**Comment by johnKHill** [comment]
It didn't

**Comment by misterdev** [comment]
@vincentaudebert do you know the reason why that doesn't work on free dynos?
