### ISSUE TITLE
Add support inline keyboard not in inline_mode

### ISSUE THREAD

**Issue by damintsew** [Naltox/telegram-node-bot#13]
Sorry I cant format code here :(

Add support for theese type of buttons (directly in chat) see picture.
![image](https://cloud.githubusercontent.com/assets/1108336/14643564/80254e1c-0657-11e6-9240-87a246eea725.png)

I tsend this message:
`$.sendMessage(funct(), {
                        parse_mode: 'Markdown',
                        reply_markup: JSON.stringify({ 
                            inline_keyboard: [
                                [{text: 'Еще факты', callback_data: 'test'}]
                            ]
                        })
                    }, (clb) => {
                        console.log(clb)
                    });`

And then here (thanks for adding) I reveive callback_data: 'test'

`tg.callbackQuerys(($) => {

 })`

But this is not very good solution. Because I want to execute editMessage and ib this siruation code may be very difficult.

Consider to change this to something like:

> $.sendMessage(funct(), {
>                         parse_mode: 'Markdown',
>                         reply_markup: markup
>                     }, (clb) => {
>                         console.log(clb)
>                     });
> 
> markup = { 
>                             inline_keyboard: [
>                                 [{text: 'Еще факты', callback: function ($) {
>                                         $.editMessage('updated text');
>                                  }]
>                             ]
>                       }

Or

> markup = { 
>                             inline_keyboard: [
>                                     { 
>                                       'Еще факты' : function ($) {  $.editMessage('updated text') }
>                                     }
>                             ]
>                }       

I have some ideas how to implement this... but needs your clarifiations. Because I wrote code and you can reject it :)

**Comment by Naltox** [comment]
Hey! I just updated the module, now you can use runInlineMenu method to create inline menus :)

**Comment by infacq** [comment]
how do I set user input right after they made their selection from inline menus? how to proceed from there
