### ISSUE TITLE
getChatMember()?

### ISSUE THREAD

**Issue by mammad2c** [Naltox/telegram-node-bot#133]
Hi,
getChatMember not working? it sends me promise but relay on Telegram Bot api, must return a chatMember object. and promise is still pending. [https://core.telegram.org/bots/api#getchatmember](https://core.telegram.org/bots/api#getchatmember)

my code : 
`'use strict'

const Telegram = require('telegram-node-bot');
const TelegramBaseController = Telegram.TelegramBaseController;
const TextCommand = Telegram.TextCommand;
const tg = new Telegram.Telegram('token');

class PingController extends TelegramBaseController {
    /**
     \* @param {Scope} $
     */
    pingHandler($) {
        $.sendMessage('pong');
        var testMember = tg.api.getChatMember($.message.chat.id, $.message.from.id);
        console.log(testMember) // result : promise {pending}
    }

```
get routes() {
    return {
        'pingCommand': 'pingHandler'
    };
}
```

}

tg.router
    .when(
        new TextCommand('ping', 'pingCommand'),
        new PingController()
    )`

**Comment by alxrm** [comment]
Yes, that's actually weird, maybe it's somehow related to the fact, that you use this lib, which returns promise.

And, it's only the assumption, you should probably call `.then()` to get the result

**Comment by mammad2c** [comment]
yea,
I changed my code and used `.then()`. 
tnx
