### ISSUE TITLE
answerInlineQuery not working? 

### ISSUE THREAD

**Issue by Montoya** [Naltox/telegram-node-bot#14]
Hi, I'm trying to do something very simple with inlineMode and not getting any results...

Here's my code: 

```
tg.inlineMode(($) => {
  var msg = $.query
  tg.answerInlineQuery($.id, [{
    text: msg
  }])
})
```

I already registered inlineMode with BotFather, by the way. When I try using inlineMode the spinner works for a while and then nothing happens. Not seeing any errors in the logs either...

**Comment by Naltox** [comment]
Hey!

 [{
    text: msg
 }]

is not valid, you can find answer types here: https://core.telegram.org/bots/api#inlinequeryresult

For your example you can use this: 

```
tg.inlineMode(($) => { 
    var msg = $.query
    tg.answerInlineQuery($.id, [{
        type: "article",
        title: msg,
        input_message_content: {
            message_text: msg
        }
    }]) 
})
```

**Comment by Montoya** [comment]
Thank you! That fixed it. It works perfectly now :)
