### ISSUE TITLE
RegexpCommand - is not installed

### ISSUE THREAD

**Issue by Yojj** [Naltox/telegram-node-bot#176]
использую из примера 
_.when(
        new RegexpCommand(new RegExp(/test/, 'g'), 'testHandler'),
        new TestController()
    )_

пишет
RegexpCommand - is not installed
     
_new RegexpCommand(new RegExp(/test/, 'g'), 'testHandler'),
            ^ ReferenceError: RegexpCommand is not defined_

подскажите, пожалуйста, как решить?
Спасибо!

**Comment by rafaelpradella** [comment]
Hi! I´m not sure if you already made it in the start of your file, but the RegexpCommand is a method inside the telegram-node-bot Class. Try calling it that way:

```
const Telegram = require('telegram-node-bot');
const RegexpCommand = Telegram.RegexpCommand;

.when(
new RegexpCommand(new RegExp(/test/, 'g'), 'testHandler'),
new TestController()
)

```
Hope it helps! ;)

**Comment by magikcypress** [comment]
Hello,

On the documentation this method is create and says that ...

```
tg.router
  .when(
      new RegexpCommand(/test/g, 'testHandler'),
      new TestController()
  )
```

 but a loggout say "error Not implemented"

Regards

**Comment by Yojj** [comment]
Hello,
 example  for works  

var reg =/ Hi | Hello | Hao | Vitayu |\b/i;

 tg.router  .when(new Telegram.RegexpCommand ( reg, 'pingCommand'),
                         new HiController()
                     )
