### ISSUE TITLE
"getMe" is not available

### ISSUE THREAD

**Issue by asajm** [Naltox/telegram-node-bot#19]
dears,

why "getMe" method is not available?

just this is the whole thing. :)
`
getMe(callback){
      this.call('getMe', {}, callback)
    }
`

**Comment by zverev** [comment]
+

**Comment by tunix** [comment]
👍 I'm up for this as well.

**Comment by tunix** [comment]
@Naltox could you please write why you're rejecting this? I need to hardcode bot's name when this service isn't available.

**Comment by Naltox** [comment]
@tunix Its available now!
