### ISSUE TITLE
Downloaded file corrupted

### ISSUE THREAD

**Issue by damintsew** [Naltox/telegram-node-bot#2]
Hello!

Trying to download file using this code:
`$.sendDocumentFromUrl(film.downloadlink, {filename: 'test.torrent', contentType: "application/octet-stream"});`
Also tried with different names and different contentTypes.
But when I receive file and open in torrent I have an error that file is corrupted.

Here is the link of file whitch I want to download (http://kino-torrent.net/load/0-0-0-1446-20). Using browser downloading is complete.

**Comment by Naltox** [comment]
Hi!

This site have redirect, so whet you trying to download torrent file from that url you will have this:

<img width="773" alt="screen shot 2016-02-13 at 17 56 32" src="https://cloud.githubusercontent.com/assets/8849761/13028263/23be2366-d27b-11e5-9800-4f202b41e88c.png">

So you need to find direct url and then send your file.

**Comment by damintsew** [comment]
hmmm... yes.
I was cofused by module 'request'. It can handle redirect situation.
So now I use request with $.sendDocument.

Maybe think how handle redirect situation ?

**Comment by damintsew** [comment]
Also consider to checking for callback in method sendDocument just as for 'caption'. 

`callback = callback ? callback : () => {}`

**Comment by Naltox** [comment]
Thanks, i will add checking for callback.
