### ISSUE TITLE
Close menu from his inside

### ISSUE THREAD

**Issue by alebertz** [Naltox/telegram-node-bot#200]
How do I close the menu inside the yes function?
` 'yes': () => {
      $.sendMessage('Test!');
     // Method to close the menu, please help me.
  }`

**Comment by rotimi-best** [comment]
All you need to do is this:
```javascript
'yes': () => { $.sendMessage('Test!', { reply_markup: JSON.stringify({ remove_keyboard: true }) });
```

Please let me know if it helps

**Comment by alebertz** [comment]
> All you need to do is this:
> 
> ```js
> 'yes': () => { $.sendMessage('Test!', { reply_markup: JSON.stringify({ remove_keyboard: true }) });
> ```
> 
> Please let me know if it helps

Thank you.
