### ISSUE TITLE
How to answer inline queries

### ISSUE THREAD

**Issue by alebertz** [Naltox/telegram-node-bot#204]
I'd like to know how to answer inline queries.

**Comment by rotimi-best** [comment]
First define it in your index.js
https://github.com/Rotimi-Best/mytodos/blob/ace490de4cd5c5a834af921bc047687863642d15/index.js#L10

Then answer to them like this
https://github.com/Rotimi-Best/mytodos/blob/ace490de4cd5c5a834af921bc047687863642d15/callbackQueries/index.js#L17

To see more about how to do it, I have a [todo bot](https://github.com/Rotimi-Best/mytodos) you can check it out, I answer inline queries.
