### ISSUE TITLE
Close keyboard to selective users

### ISSUE THREAD

**Issue by matiasperz** [Naltox/telegram-node-bot#205]
Im trying to make a poll bot with the markup menu but I want to close the that menu when someone replyes, making the menu unaccesible so the oneTimeKeyboard is not an option.
I read the reply_markup with the remove_keyboard and selective options would make it but it isn't working, here is my code:

![imagen](https://user-images.githubusercontent.com/43894343/54442234-0a10af00-471d-11e9-918c-c3288b670a7f.png)

**Comment by rotimi-best** [comment]
I havn't tested it but I have 2 guesses, try swapping `data.sendMessage` with `$.sendMessage`. And in case it doesn't work instead of sending a picture, paste the code here inorder for me to test it locally.
