### ISSUE TITLE
support for webHooks

### ISSUE THREAD

**Issue by archimedix** [Naltox/telegram-node-bot#21]
there is a plan for implementing webHooks?

**Comment by gvitali** [comment]
I subscribe to the issue! It would be very nice and useful to have webhooks supported.

**Comment by Naltox** [comment]
Will be!

**Comment by Tpona** [comment]
Привет!
Пока в процессе? Или есть уже функционал?

**Comment by Naltox** [comment]
@Tpona Привет! Пока нету и не факт что будет, не вижу особого смысла в них

**Comment by Tpona** [comment]
У меня был глюк недавно, перестал работать бот на айфонах, причину не нашел, вот и задумался, все же надёжнее когда тебе кидают сообщение, а не ты пытаешься запросить. Странно конечно, были обновления телеграмма, может с ними было связано, хотя не понятно как.

**Comment by Naltox** [comment]
Ну это с клиентом беда была, скорее всего, апи конда падает - все боты перестают работать. И там уже без разницы вебхуки или нет.
