### ISSUE TITLE
Unlimited number of params at routing

### ISSUE THREAD

**Issue by dbalduini** [Naltox/telegram-node-bot#22]
Do we have some way of receiving any number of args from commands?

```
when(['/sum *'', ...]
```

Example:

```
/sum 1 2 3 4 5
```

**Comment by Naltox** [comment]
I think we can add this in new version

**Comment by tunix** [comment]
Is this added? It'd be nice if you could add issue numbers in your commits or PR's so that it can be easier to track for others.

**Comment by dbalduini** [comment]
I could read a list of args by doing this. I don't think you need to implement something new if you just add this to the README

```
/sum 1 2 3 4

let params = $.args.split(' ')

=> ['1', '2', '3', '4']
```
