### ISSUE TITLE
Wildcard Commands

### ISSUE THREAD

**Issue by tunix** [Naltox/telegram-node-bot#27]
Hi There,

Thanks for the great library in the first place. Would you consider adding wildcard commands such as:

```
/dl_12351
```

Such commands exist in @music bot and is useful for bots that allows action on inline query answers.

**Comment by Naltox** [comment]
Hi!
I think you can use $.waitForRequest method for this. I mean you can send the message with this commands and wait for the next message from user with command

**Comment by tunix** [comment]
@Naltox - 👍 seems to work for now, thanks!
