### ISSUE TITLE
clear keyboard?

### ISSUE THREAD

**Issue by paOol** [Naltox/telegram-node-bot#30]
I'm doing a .runMenu , and basically would like a way to clear the keyboard incase the user wants to cancel or enters something invalid.

is there a way to do this? I looked at the library and couldn't find any method of doing so.

```
'anyMatch' : ($) => {
   // $.clearKeyboard or something
}
```

**Comment by Naltox** [comment]
Sorry, but in telegram API you cant just clean keyboard, you need to send some message with ReplyKeyboardHide: https://core.telegram.org/bots/api#replykeyboardhide

**Comment by paOol** [comment]
```

var clearKeyboard = {reply_markup: JSON.stringify({hide_keyboard: true }) }

'anyMatch' : ($) => {
   $.sendMessage( ``, clearKeyboard  )
}

```

in case anyone was looking for a solution,  I got it working like this.

**Comment by 0rangefist** [comment]
@paOol , the API returns an error if the message is empty.
Api error: Body: { ok: false,
  error_code: 400,
  description: 'Bad Request: Message text is empty' }

**Comment by paOol** [comment]
Ya, the empty string no longer works in v3.

So I send the message 

'''
$.sendMessage( action cancelled``, clearKeyboard  )
'''
