### ISSUE TITLE
Adding ability to show custom keyboards in forms

### ISSUE THREAD

**Issue by tunix** [Naltox/telegram-node-bot#33]
I'm considering adding a PR as well but would like to know your thoughts about it in the first place. Would you consider adding support for custom keyboards in forms?

Considering below form in which you get a boolean answer (yes/no):

```
...
now: {
    q: "Would you want to do this now? (y/n)",
    error: "...",
    validator: (input, callback) => {...}
},
...
```

I think we can add a special attribute (keyboard?) here to show a custom keyboard?

**Comment by danieltorrer** [comment]
@tunix For me this piece of code worked, I don't know if this is what you are looking for

```
var form = {
        civil: {
            q: 'Pregunta',
            error: 'Intenta de nuevo',
            keyboard: [
                [{ text: 'Soltero'}], 
                [{ text: 'Casado' }], 
                [{ text: 'Divorciado' }], 
            ],
            validator: (input, callback) => {
                if(input.text) {
                    callback(true);
                    return;
                }

                callback(false);
            }
        }
}
```

**Comment by tunix** [comment]
@danieltorrer yes it does! thanks!
