### ISSUE TITLE
Undefined number of args?

### ISSUE THREAD

**Issue by haarspalter** [Naltox/telegram-node-bot#43]
Is there any way to route messages that may have 1 to n arguments? Putting the args into ".." or '.." seems not to work.

**Comment by Naltox** [comment]
Hi! You can declare standard command with no arguments and any additional args will be in args field in scope. 

For example: 

``` js
tg.router.
    when('/test', 'TestController')

tg.controller('TestController', ($) => {
    tg.for('/test', () => {
        console.log($.args)
    })
})
```
