### ISSUE TITLE
Remove/destroy menu

### ISSUE THREAD

**Issue by dleonext** [Naltox/telegram-node-bot#46]
Hello.
I created a menu with `runMenu()`. There's a way to completely destroy or remove this menu when the user clicks a specific menu button?

Thanks in advance.

Cheers.

**Comment by litinskii** [comment]
@dleonext pass one_time_keyboard to options when create menu (https://core.telegram.org/bots/api#replykeyboardmarkup)

**Comment by dleonext** [comment]
@w-site thanks for the reply.

> The keyboard will still be available, but clients will automatically display the usual letter-keyboard in the chat – the user can press a special button in the input field to see the custom keyboard again.

Any way to completely destroy the menu?

Cheers

**Comment by litinskii** [comment]
@dleonext Yep, so if you want destroy use https://core.telegram.org/bots/api#replykeyboardhide try pass hide_keyboard:true to options

**Comment by dutu** [comment]
passing `hide_keyboard:true` to options does not restore the keyboard to the usual one.
yes, https://core.telegram.org/bots/api#replykeyboardhide seem to do the trick, but how can `ReplyKeyboardHide` be used?

**Comment by 8of** [comment]
@dutu 
In order to close the menu after the button is clicked, you can use `oneTimeKeyboard: true`

``` js
$.runMenu({
    message: 'Select:',
    oneTimeKeyboard: true,
    options: {
        parse_mode: 'Markdown' // in options field you can pass some additional data, like parse_mode
    },
    'Exit': {
        message: 'Do you realy want to exit?',
        resizeKeyboard: true,
        'yes': () => { },
        'no': () => { }
    }
})
```

**Comment by rotimi-best** [comment]
The solutions here are how to hide and the question is how to destroy. If I understand destroy it means that the menu should no longer be accessible to the user.

I did it this way [here](https://github.com/Naltox/telegram-node-bot/issues/202#issuecomment-439879758)

**Comment by ali-safapour** [comment]
The message containing the menu button(s) must be removed. The menu will be destroyed afterwards.
