### ISSUE TITLE
Passing additional options to the sendMessage method is not working.

### ISSUE THREAD

**Issue by nerezo** [Naltox/telegram-node-bot#48]
Hi,
I want to send "disable_web_page_preview" option to the sendMessage method. Not able to pass this option with sendMessage. Any option can not be add too.

When I added this option manually on the below object, it works properly.
`198:   var preparedOptions = this._prepareOptions(options, callback, {`
`199:      chat_id: chatId,`
`200:      text: text`
`201:   })`

Regards,
Okan.

**Comment by nerezo** [comment]
Hi, I think that this has fixed on the next releases?

**Comment by Naltox** [comment]
@nerezo Hey, its fixed, read docs please

**Comment by nerezo** [comment]
hey, thanks for your interest. i am going to read all of the main guide.
