### ISSUE TITLE
Неизвестная команда, ошибка

### ISSUE THREAD

**Issue by Orel2888** [Naltox/telegram-node-bot#57]
Может стоит фиксануть выброс ошибки при неизвестной команде? `Ping` -> `error TypeError: Cannot read property 'name' of undefined`

**Comment by Orel2888** [comment]
И еще регистра независимость бы не помешала.

**Comment by Naltox** [comment]
Эта ошибка падает когда у тебя в роутере объявлена команда и объявлен контроллер для нее, но в роутере нет функции для этой команды и нет функции handle

**Comment by Orel2888** [comment]
Неа, из доки

``` js
class PingController extends TelegramBaseController {

    /**
     * @param {Scope} $
     */
    pingHandler($) {
        $.sendMessage('pong')
    }

    get routes() {
        return {
            'ping': 'pingHandler'
        }
    }
}

tg.router
    .when(['ping'], new PingController());
```

Пишем боту ping, ок. Пишем Ping, выброс ошибки выше.

**Comment by Naltox** [comment]
@Orel2888 Ошибку поправил, а вот насчет регистра - мне кажется в таких случаях лучше RegExp использовать

**Comment by Orel2888** [comment]
Осталась (

**Comment by Orel2888** [comment]
Думаю списывать на RgExp не стоит, кому понадобится такая фича, как выполнение разной логике для команд `Привет привет ПриВет` ?

**Comment by Naltox** [comment]
@Orel2888 Теперь точно фикс
