### ISSUE TITLE
ReferenceError: Proxy is not defined

### ISSUE THREAD

**Issue by ilyagru** [Naltox/telegram-node-bot#61]
Здравствуйте, при запуске с пинг-понг вылазит ошибка:

return new Proxy(this, locHandler)
ReferenceError: Proxy is not defined
at new Ivan
Ivan.js
at new Telegram
Telegram.js

**Comment by Naltox** [comment]
@ilyagru Привет! Обновите node.js

**Comment by ilyagru** [comment]
не помогло

**Comment by Naltox** [comment]
@ilyagru А на какую обновили? Что выдает node -v?

**Comment by ilyagru** [comment]
4.4.6, как на сайте

**Comment by Naltox** [comment]
@ilyagru 4.4.6 это LTS, последняя - 6.2.2

**Comment by ilyagru** [comment]
она же не stable? или всё ок, можно ставить спокойно?

**Comment by ilyagru** [comment]
извиняюсь, если задаю глупые вопросы, просто я джуниор )

**Comment by Naltox** [comment]
@ilyagru она stable, ставьте спокойно

**Comment by ilyagru** [comment]
спасибо

**Comment by bushev** [comment]
А поддержки версий младше чем 6 не будет? :-(

**Comment by Naltox** [comment]
@bushev Нет, а смысл?
