### ISSUE TITLE
How to reply to a inline button

### ISSUE THREAD

**Issue by LBreda** [Naltox/telegram-node-bot#63]
Hi, 

I can't understand how to reply to a inline button, making the spinner disappear. In the previous version, I did it with tg.answerCallbackQuery($.id)

**Comment by kamikazechaser** [comment]
Following

**Comment by Naltox** [comment]
@LBreda @kamikazechaser You can use `answerCallbackQuery` method in api for that:

``` js
tg.api.answerCallbackQuery(callbackId, options)
```

**Comment by kamikazechaser** [comment]
``` js
  callback: (callbackQuery) => {
                        $.sendMessage('*Some Stuff Here*', {
                            parse_mode: 'Markdown'
                        })
                        tg.api.answerCallbackQuery(callbackId, { text: 'Showing Help', show_alert: true })
```

Am i doing it right? Cause it doesnt seem to be working for me

**Comment by infacq** [comment]
following

**Comment by LBreda** [comment]
@kamikazechaser What is `callbackId`?

**Comment by kamikazechaser** [comment]
@LBreda Unique identifier for the query to be answered

**Comment by LBreda** [comment]
@kamikazechaser try `callbackQuery.id`, it works for me.

**Comment by kamikazechaser** [comment]
Worked like a charm!

**Comment by rotimi-best** [comment]
Thanks very cool
