### ISSUE TITLE
Example does’t run

### ISSUE THREAD

**Issue by marcoka2000** [Naltox/telegram-node-bot#67]
Hi,

i tried to run the example from the readme.md but even that gives me an error back 

> const Telegram = require('telegram-node-bot')
> ^^^^^
> SyntaxError: Use of const in strict mode.
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:945:3

… also tried running without strict mode etc.

Am i the only one getting this problems? 

Best regards,
Marco

**Comment by Naltox** [comment]
@AlphonsPho Hi!

You need to update your node!

**Comment by marcoka2000** [comment]
oh, that easy.
sorry for bothering.
