### ISSUE TITLE
/start === /startttttt

### ISSUE THREAD

**Issue by sergeykvalarstudios** [Naltox/telegram-node-bot#70]
Hi!
If I listen "/start" command `tg.router.when(['/start']` and user sent any word started on "/start", for example "/starttttdds", it will be processed like a "/start"

**Comment by Naltox** [comment]
Will fix that, thanks!

**Comment by Naltox** [comment]
@sergeykvalarstudios Hey, i have thought about that, there is a problem when we have command with args, i mean if user send `/start some args here` may be you want that args.

**Comment by VitaliyR** [comment]
@Naltox maybe we should refactor that _testCommand method? Because it is really weird to substr a string and removing route command from it and think that other things which are left are arguments.
