### ISSUE TITLE
any and otherwise don't work

### ISSUE THREAD

**Issue by MaximBatanov** [Naltox/telegram-node-bot#71]
error TypeError: Cannot read property 'toString' of undefined
    at OtherwiseController.methodForCommand (.../TelegramBaseController.js:59:34)
    at controllers.forEach.e (.../MessageUpdateProcessor.js:63:44)
    at Array.forEach (native)
    at _getSession.then.session (.../MessageUpdateProcessor.js:54:33)
    at process._tickCallback (internal/process/next_tick.js:103:7)

I added a quick fix:
(TelegramRouter.js)
    commandNameForUpdate(update) {
       /_code here_/
        **if( this._otherwiseController ) return 'otherwise';
        else if( this._anyController ) return 'any';**
    }

**Comment by Naltox** [comment]
@MaximBatanov 
Hi! What version of module you are using? And can you show your router?

**Comment by MaximBatanov** [comment]
Version: 3.0.4

**Comment by Naltox** [comment]
@MaximBatanov Try to update, if that does not help show me your router please.

**Comment by MaximBatanov** [comment]
Version: 3.0.7 - the same error.
My controller:
class AnyController extends Telegram.TelegramBaseController {
  anyHandler( $ ) {
    console.log( JSON.stringify($.message) );
  }
  get routes() {
    return {
      'any': 'anyHandler',
    }
  }
}
bot.router.any( new AnyController() );

**Comment by Naltox** [comment]
@MaximBatanov Any controllers cant have routes

**Comment by Naltox** [comment]
@MaximBatanov use that like this: 

``` js
class AnyController extends Telegram.TelegramBaseController {
    handle($) {
        //handle all messages here
    }
}

tg.router
    .any(new AnyController())
```

**Comment by MaximBatanov** [comment]
Thanks. It's work.
