### ISSUE TITLE
Best practice to access other controllers methods

### ISSUE THREAD

**Issue by Konfuze** [Naltox/telegram-node-bot#72]
What will be the best practice to access methods of one controller from another without creating a new instance?

For example I want to access methods of `SomethingController` from `StartController` which displays the '/start' menu.

In previous version there was a method `$.routeTo('/something')`

**Comment by Naltox** [comment]
@Konfuze 
Hi!
There is no such opportunity yet, but i will add `routeTo` method soon.

**Comment by Konfuze** [comment]
It would be great.
Thank's for quick response!

**Comment by cnavigato** [comment]
We use of $.routeTo extensively in the old version.  Looking forward to seeing this method in version 3. Thanks you for developing this npm module!

tg.controller('MenuController', ($) => {
    tg.for('/menu', () => {
        $.runMenu({
            message: '---Keyboard Menu Available---',
            layout: 3,
            'Bud': () => {$.routeTo("/bud");}, 
            'Edibles': () => {$.routeTo("/edibles");},
            'Wax': () => {$.routeTo("/wax");},
            'Specials': () => {$.routeTo("/specials");},
            'Restart': () => {$.routeTo("/restart");},
            'Feedback': () => {$.routeTo("/feedback");}, 
            'Help': () => {$.routeTo("/help");}, 
            'Upload': () => {$.routeTo("/upload");},
            'Payment': () => {$.routeTo("/bitcoin");},
        });  
    });
});

**Comment by muety** [comment]
Has the $.routeTo method been added yet? Looking forward to something like that, too.

**Comment by osadchiynikita** [comment]
As @Naltox suggested, there is emulateUpdate method, which can be used like this:

const tg = new Telegram.Telegram(token);
tg.emulateUpdate($.update)

**Comment by herenickname** [comment]
@osadchiynikita and how to route? Where I can define the route?
