### ISSUE TITLE
how to write emoji

### ISSUE THREAD

**Issue by infacq** [Naltox/telegram-node-bot#75]
how to write emoji in `$.sendMessage`?

**Comment by kamikazechaser** [comment]
Just copy and paste emojis into your `textfield` 🔰🌀🔌As you can see here.

`$.sendMessage('🔰🌀🔌')`

**Comment by infacq** [comment]
is the right way? haha

**Comment by kamikazechaser** [comment]
Try it, I am serious , thats the only way

**Comment by infacq** [comment]
ok then. tried it already. it works
