### ISSUE TITLE
Persistent storage + lack of documentation

### ISSUE THREAD

**Issue by amsonline** [Naltox/telegram-node-bot#76]
Hello
How can I use a persistent storage? Sessions seem to be destroyed every time. I want to save each user's settings (mainly their selected language) but I cannot find a correct (and clean) way to do that.

By the way, the documentation is not very powerful. For example, it doesn't have enough samples and most of functions are not described in details.

**Comment by Naltox** [comment]
@amsonline 
Hi! You can create your own storage, that will use some database: https://github.com/Naltox/telegram-node-bot#sessions
