### ISSUE TITLE
InputFile is not defined

### ISSUE THREAD

**Issue by yuri92** [Naltox/telegram-node-bot#77]
Hi,
How can we include "InputFile" to use the method `InputFile.byUrl('URL', 'image.jpg')`?

Many thanks,
Yuri

**Comment by Naltox** [comment]
@yuri92  
Fixed that!

**Comment by sadeghmohebbi** [comment]
hi
how can i include it!?

Error: Cannot find module './InputFile'
TypeError: Cannot read property 'byFilePath' of undefined
ReferenceError: InputFile is not defined

thanks a lot
