### ISSUE TITLE
TypeError: Cannot read property 'error_code' of undefined

### ISSUE THREAD

**Issue by infacq** [Naltox/telegram-node-bot#78]
I use Ubuntu 14.04 to host the bot. I'm not sure whether this error cause by what

``` bash
node_modules/telegram-node-bot/lib/api/TelegramApi.js:111
            if (body.error_code) {
                    ^
```

my `node -v` is `6.2.2` and npm is `3.9.5`

I also try to downgrade node to `5.12.0` and npm is `3.8.6` but hit another error

`ReferenceError: Proxy is not defined`

``` bash
/node_modules/telegram-node-bot/lib/localization/Ivan.js:41
        return new Proxy(this, locHandler)
                   ^
```

**Comment by kamikazechaser** [comment]
#68

**Comment by Naltox** [comment]
@infacq Just added logging for that case, update module and check the logs.
