### ISSUE TITLE
Как получить информацию о пользователе?

### ISSUE THREAD

**Issue by Tpona** [Naltox/telegram-node-bot#80]
Доброго дня!

Понадобилось мне получить first_name/username итд.
$.getChat() возвращает промис, пока что я не в курсе как с ними работать )) 
Был бы очень рад примеру, так как подобные вещи в документации не описаны.
Возможно и не будут, так как это больше относится к знаниям ES6.
По большому счету хотелось бы увидеть пример как воспользоваться вызовами для получения информации о пользователе, чате итп

Благодарю заранее )

**Comment by Naltox** [comment]
Привет!

$.getChat() - это методв в [API](https://core.telegram.org/bots/api#getchat), он отдает [Chat](https://core.telegram.org/bots/api#chat)

Использовать можно так: 

``` js
$.getChat()
    .then(chat => {
        console.log(chat)
    })
```

По сути тот же объект есть сразу в `$` - `$.message.chat`
