### ISSUE TITLE
409 webhook vs pollling

### ISSUE THREAD

**Issue by sersasa** [Naltox/telegram-node-bot#83]
Hi there,
I have set a webhook for my bot from a browser using telegram api before using this code, and Telegram return an OK answer.

Than, when I use this code (great code for instance, thanks!) I get this error:
[warn]
Api error: Body: { ok: false,
  error_code: 409,
  description: 'Conflict: another webhook is active' }

How can I resolve it? Can I use webhook with your code?
Can I only use polling-method instead webhook!?
Thanks in advaced!

**Comment by Tpona** [comment]
It seems, that this framework works only throught pooling method

**Comment by Konfuze** [comment]
@sersasa try to pass an empty string to webhook url parameter (https://core.telegram.org/bots/api#setwebhook)

**Comment by sersasa** [comment]
But that's for "unset" webhook (i.e., use polling instead webhook) and I don't want that!
I want to use the more efficient way for bots: webhook.
Is this example of bot able to use webhook technic? How?
Hundred thanks in advanced!! (apart from the kind of answer you'll give me :))

**Comment by LBreda** [comment]
@sersasa This framework does not support webhooks.
