### ISSUE TITLE
the code out of the box doesn't work

### ISSUE THREAD

**Issue by heidarsaleh** [Naltox/telegram-node-bot#86]
Hello,
I tried the attached sample and I got an error: Cant find controller for update, code is below:

const Telegram = require('telegram-node-bot')
const TelegramBaseController = Telegram.TelegramBaseController
const tg = new Telegram.Telegram('I placed my token here')

class PingController extends TelegramBaseController {
    /**
     \* @param {Scope} $
     */
    pingHandler($) {
        $.sendMessage('pong')
    }

```
get routes() {
    return {
        'ping': 'pingHandler'
    }
}
```

}

tg.router
    .when(['ping'], new PingController())

**Comment by alxrm** [comment]
It's just a warning, you don't have a handler for this command

I've just tested this, it works fine
