### ISSUE TITLE
Answering callback query?

### ISSUE THREAD

**Issue by VitaliyR** [Naltox/telegram-node-bot#88]
Hello. 
It is still not clear how to handle callbacks from inline buttons.
In each callback I'm using

``` javascript
callback: cb => {
  $.api.answerCallbackQuery(cb.id)
}
```

so the button in Telegram will stop 'spinning'. 

Are there any solution out the box to not write that `answerCallbackQuery` each time?

**Comment by kamikazechaser** [comment]
#63 This issue has already been discussed and sorted out.

**Comment by VitaliyR** [comment]
Is this a solution - each time I should write it? Really? For each button?
