### ISSUE TITLE
[error]  api request error: Body: undefined

### ISSUE THREAD

**Issue by qadir-genetech** [Naltox/telegram-node-bot#91]
I have made a bot using your awesomely coded library for bots.

I have made a bot which response as blow

Hi =>bot reply with, Hello
Hello => bot reply with, Hello
Bye => bot reply with, Have a nice day
Movie => open up a menu to select a movie type
Image => will send you a demo image
Location => will send you a google map with specified lat, lon

After some time bot stops responding and I got the error on my terminal 

`[error]   
api request error: Body: undefined
Error: Error: connect ETIMEDOUT 149.154.167.200:443
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)`

any suggestion.

I have to restart my bot to respond again

**Comment by Naltox** [comment]
Just updated module, think that will help
