### ISSUE TITLE
bot stops after "Api error: Body: { ok: false, error_code: 401, description: 'Unauthorized' }"

### ISSUE THREAD

**Issue by dutu** [Naltox/telegram-node-bot#92]
The error below occurs and bot stops. The issues goes away after bot restart (only)

```
[warn]    
Api error: Body: { ok: false, error_code: 401, description: 'Unauthorized' } 
```

**Comment by Orel2888** [comment]
Same problem

**Comment by Naltox** [comment]
You can get this error when you don't pass token to api, or there is a bug in Telegram server.

**Comment by dutu** [comment]
yes, it's due to an improper response from Telegram server. The situation should be handled so that the bot retries again after some time

**Comment by Naltox** [comment]
@dutu Library can retry requests, but only when there is a network problem, we cant detect that in this case this is an error from tg side
