### ISSUE TITLE
bot stops after "Api error: Body: { ok: false,  error_code: 500,  description: 'Internal server error: restart' } 

### ISSUE THREAD

**Issue by dutu** [Naltox/telegram-node-bot#93]
After below error occurs the bot stops and normal functionality is possible only after the application is manually restarted

```
Api error: Body: { ok: false, 
  error_code: 500, 
  description: 'Internal server error: restart' } 
```

**Comment by Naltox** [comment]
@dutu 
Just updated module, hope that will fix this problem

**Comment by dutu** [comment]
That's understood, but the expectation is that the error is handled without having the bot stopped.

Having the bot stopped should definitively be avoided.

**Comment by Orel2888** [comment]
This error just in process working

**Comment by Naltox** [comment]
@dutu 

That's right, this error is handled by retrying the request and the bot doesn't stop.
