### ISSUE TITLE
How to recover results from forms?

### ISSUE THREAD

**Issue by Charlyo** [Naltox/telegram-node-bot#96]
I understand that the console.log after the .runForm gives the input of the user response of the forms. However, no result is displayed...

**Comment by kamikazechaser** [comment]
Save it to a database of your choice.

**Comment by Charlyo** [comment]
Following the example: 
const form = {
    name: {
        q: 'Send me your name',
        error: 'sorry, wrong input',
        validator: (message, callback) => {
            if(message.text) {
                callback(true, message.text) //you must pass the result also
                return
            }

```
        callback(false)
    }
},
age: {
    q: 'Send me your age',
    error: 'sorry, wrong input',
    validator: (message, callback) => {
        if(message.text && IsNumeric(message.text)) {
            callback(true, toInt(message.text))
            return
        }

        callback(false)
    }
}
```

}

$.runForm(form, (result) => { 
// *
    console.log(result)
})

This last console.log, should show the user input in each question of the form. However, \* never executes.

**Comment by aed86** [comment]
Seems there are a bug in the validator:
` if(message.text && IsNumeric(message.text)) {`
...
`ReferenceError: isNumeric is not defined`

**Comment by edakhmetgareev** [comment]
I think the problem in the validator function. IsNumber and toInt functions are not defined in js by default.

**Comment by ArgeSwarge** [comment]
In my project i use object :
`var form_data = new Object()`

Form constant :
`name:
    {
        q: 'Enter name',
        error: 'sorry, wrong input',
        validator: (message, callback) =>
        {
           if(message.text)
            {
                callback(true, message.text)
                {
                    form_data.name = message.text;
                    return form_data.name
                }

            }
        callback(false)
        }
    }`

Then u can do this stuff :
$.sendMessage
            (
                'The Data: \n'+
                'Name - '+form_data.name                
            )
