### ISSUE TITLE
.otherwise (Cannot read property 'toString' of undefined)

### ISSUE THREAD

**Issue by TemaSM** [Naltox/telegram-node-bot#99]
Found bug with `TelegramRouter().otherwise(controller)` method.

Function argument  `controller` is instance of class `TelegramBaseController`, which has function `methodForCommand()` implemented for binding commands -> routes -> actions.

So, when we call `tg.router.otherwise(new OtherwiseController())`, if statement on [TelegramBaseController.js#L59](https://github.com/Naltox/telegram-node-bot/blob/master/lib/mvc/TelegramBaseController.js#L59) will fire `TypeError: Cannot read property 'toString' of undefined`, because as argument to `.otherwise()` we provided object of `Controller`, not an `command` param of string type, that's why `command.toString()` firing Error.

**Gonna fix it today & send PR** :ok_hand:

**Comment by xiaoziguys** [comment]
i had the same problem
